version: '3.5'

services:
  captain-hook:
    hostname: captain-hook
    build:
      context: ./
      dockerfile: Dockerfile
    command: /captain-hook/entrypoint.sh
    environment:
      - ENVIRONMENT
    volumes:
      - ./.nyc:/captain-hook/.nyc
      - ./coverage:/captain-hook/coverage
      - ./data:/captain-hook/data
      - ./.nyc_output:/captain-hook/.nyc_output
