version: '3.5'

services:
  captain-hook:
    hostname: captain-hook
    build:
      context: ./
      dockerfile: Dockerfile
    command: /captain-hook/entrypoint.sh
    environment:
      - ENVIRONMENT
