version: '3.5'

services:
  captain-hook:
    hostname: captain-hook
    container_name: captain-hook
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    command: /captain-hook/entrypoint.sh
    environment:
      - ENVIRONMENT
    volumes:
      - ./data:/captain-hook/data:rw
