name: 'Run tests'

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install --save-dev
    - run: npm test
    - run: npm run coverage
    - run: ENVIRONMENT=testing docker-compose up --build --exit-code-from captain-hook

    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov