name: 'Run tests'

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'

  run-tests:
    runs-on: ubuntu-latest
  
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm test
    - run: ENVIRONMENT=testing docker-compose up --build
    - run: npm run coverage

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
